import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';
import Header from '../components/layout/header/Header';
import NextNprogress from '@/components/library/nextNprogress/NextNprogress';
import SonnerToast from '@/components/library/sonnerToast/SonnerToast';
import { MiddleFooter } from '@/components/layout/footer/MiddleFooter';
import { Footer } from '@/components/layout/footer/Footer';

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={lexend.className}>
        <NextNprogress>
          <Header />
          <main className='flex flex-col min-h-screen'>
            <div className='flex-1'>
              {children} <SonnerToast />
            </div>
          </main>
          {/* footer */}
          <MiddleFooter />
          <Footer />
        </NextNprogress>
      </body>
    </html>
  );
}
